name: Traffic monitor

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron:  '27 16 * * *'
  workflow_dispatch:

jobs:
  detect-traffic:
    runs-on: ubuntu-latest
    steps:

    # Check out repo
    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Build traffic detector image
      shell: bash
      run: |
          docker build \
              -f Dockerfile \
              -t aid-2025-10-29 \
              .

    - name: Run traffic detector
      shell: bash
      run: |
          docker run --rm \
              --privileged \
              --env OUTPUT_DIRECTORY=$(pwd) \
              -v $(pwd):$(pwd) \
              aid-2025-10-29

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: traffic-picture
        path: traffic.jpg
        retention-days: 7
